-- Drop table if exists to ensure clean state
DROP TABLE IF EXISTS "funding_requests" CASCADE;

-- Create funding_requests table with enhanced fields for  review
CREATE TABLE "funding_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int NOT NULL,
  "investor_id" int,
  "amount" decimal(15,2) NOT NULL,
  "status" varchar(50) DEFAULT 'Pending',
  "funding_stage" varchar(50),
  "description" text,
  "requested_at" timestamp DEFAULT (now()),
  "reviewed_at" timestamp,
  "reviewed_by" int,
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  CONSTRAINT fk_funding_project 
    FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE,
  CONSTRAINT fk_funding_investor 
    FOREIGN KEY ("investor_id") REFERENCES "users" ("id") ON DELETE SET NULL,
  CONSTRAINT fk_funding_reviewer 
    FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

-- Create indexes for better query performance
CREATE INDEX idx_funding_project ON "funding_requests"("project_id");
CREATE INDEX idx_funding_status ON "funding_requests"("status");
CREATE INDEX idx_funding_stage ON "funding_requests"("funding_stage");
CREATE INDEX idx_funding_created ON "funding_requests"("created_at");
