-- Create public_submissions table (contact + newsletter forms)
CREATE TABLE IF NOT EXISTS public_submissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255),
  message TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Add index for faster inbox queries
CREATE INDEX IF NOT EXISTS idx_public_submissions_type ON public_submissions(type);
CREATE INDEX IF NOT EXISTS idx_public_submissions_created_at ON public_submissions(created_at DESC);
