CREATE TABLE "announcements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "body" text NOT NULL,
  "cover_image" varchar(255),
  "published_at" timestamp,
  "author_id" INT REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);