CREATE TABLE IF NOT EXISTS cohorts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'startup',
  start_date DATE,
  end_date DATE,
  application_deadline DATE,
  status VARCHAR(50) NOT NULL DEFAULT 'upcoming',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cohorts_status ON cohorts(status);