-- Migration: Gallery CMS (UR-B8 / UR-F6)
-- gallery_items: CMS-managed photos shown on the public Photo Gallery page.
CREATE TABLE IF NOT EXISTS gallery_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  image_url VARCHAR(500) NOT NULL,
  category VARCHAR(100) DEFAULT 'General',
  is_published BOOLEAN DEFAULT FALSE,
  display_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Fast public listing of published items in display order
CREATE INDEX IF NOT EXISTS idx_gallery_items_published_order ON gallery_items(is_published, display_order);
