ALTER TABLE funding_requests
  ADD COLUMN IF NOT EXISTS approved_amount DECIMAL(15,2),
  ADD COLUMN IF NOT EXISTS founder_action VARCHAR(50);

CREATE TABLE IF NOT EXISTS funding_negotiations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funding_request_id INT NOT NULL REFERENCES funding_requests(id) ON DELETE CASCADE,
  sender_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  sender_role VARCHAR(50) NOT NULL,
  message TEXT,
  proposed_amount DECIMAL(15,2),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_negotiations_funding_request ON funding_negotiations(funding_request_id);