CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "user_code" varchar(255) UNIQUE,
  "email" varchar(255) UNIQUE,
  "password" varchar(255),
  "role" varchar(50) DEFAULT 'entrepreneur',
  "profile_image" varchar(255),
  "expertise" varchar(255),
  "company" varchar(255),
  "bio" text,
  "status" varchar(50) DEFAULT 'active',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "domain" varchar(100),
  "stage" varchar(50) DEFAULT 'Idea',
  "status" varchar(50) DEFAULT 'Pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "project_entrepreneurs" (
  "project_id" int,
  "user_id" int,
  "role_in_project" varchar(50)
);

CREATE TABLE "workshops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "trainer_id" int,
  "schedule" timestamp,
  "capacity" int,
  "category" varchar(100) DEFAULT 'General',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "workshop_attendance" (
  "workshop_id" int,
  "user_id" int,
  "attended_at" timestamp DEFAULT (now()),
  "feedback" text
);

CREATE TABLE "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "type" varchar(50),
  "description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "project_resources" (
  "project_id" int,
  "resource_id" int,
  "allocated_at" timestamp DEFAULT (now())
);

CREATE TABLE "funding_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int,
  "investor_id" int,
  "amount" decimal(15,2),
  "status" varchar(50) DEFAULT 'Pending',
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "type" varchar(50),
  "message" text,
  "read" boolean DEFAULT FALSE,
  "created_at" timestamp DEFAULT (now())
);



CREATE TABLE "session" (
    "sid" varchar NOT NULL COLLATE "default",
    "sess" json NOT NULL,
    "expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);



ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid");

ALTER TABLE "project_entrepreneurs" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_entrepreneurs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workshops" ADD FOREIGN KEY ("trainer_id") REFERENCES "users" ("id");

ALTER TABLE "workshop_attendance" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "workshop_attendance" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "project_resources" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");

ALTER TABLE "funding_requests" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "funding_requests" ADD FOREIGN KEY ("investor_id") REFERENCES "users" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

CREATE TABLE "activity_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "action_type" varchar(100) NOT NULL,
  "details" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "analytics_metrics" (
  "metric_key" varchar(100) PRIMARY KEY,
  "metric_value" int DEFAULT 0,
  "updated_at" timestamp DEFAULT (now())
);

ALTER TABLE "activity_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;
