-- Drop any duplicate/old columns first
ALTER TABLE workshops DROP COLUMN IF EXISTS mentor;

-- Add missing columns to workshops table
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS mentor_name VARCHAR(255);
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS start_time TIME;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS end_time TIME;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'scheduled';
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS enrolled_count INT DEFAULT 0;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

-- Create workshop_enrollments table
CREATE TABLE IF NOT EXISTS workshop_enrollments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workshop_id INT NOT NULL,
  entrepreneur_id INT,
  entrepreneur_name VARCHAR(255),
  entrepreneur_email VARCHAR(255),
  enrollment_date TIMESTAMP DEFAULT NOW(),
  attended BOOLEAN DEFAULT FALSE,
  feedback_rating INT,
  feedback_comment TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (workshop_id) REFERENCES workshops(id) ON DELETE CASCADE
);

-- Create workshop_feedback table
CREATE TABLE IF NOT EXISTS workshop_feedback (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workshop_id INT NOT NULL,
  enrollment_id INT,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  FOREIGN KEY (workshop_id) REFERENCES workshops(id) ON DELETE CASCADE,
  FOREIGN KEY (enrollment_id) REFERENCES workshop_enrollments(id) ON DELETE CASCADE
);

-- Add index for better query performance
CREATE INDEX IF NOT EXISTS idx_workshop_enrollments_workshop_id ON workshop_enrollments(workshop_id);
CREATE INDEX IF NOT EXISTS idx_workshop_feedback_workshop_id ON workshop_feedback(workshop_id);
