-- ============================================
-- MENTORS TABLES MIGRATION
-- Created: 2026-02-15
-- Description: Create mentors table and related junction tables
-- ============================================


CREATE TABLE IF NOT EXISTS "mentors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "phone" VARCHAR(50),
  "expertise" VARCHAR(100),
  "bio" TEXT,
  "linkedin_url" VARCHAR(500),
  "years_of_experience" INT,
  "availability" VARCHAR(50),
  "status" VARCHAR(50) DEFAULT 'active',
  "projects_count" INT DEFAULT 0,
  "workshops_count" INT DEFAULT 0,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mentor_user 
    FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL,
  CONSTRAINT chk_mentor_status CHECK (status IN ('active', 'inactive'))
);


CREATE TABLE IF NOT EXISTS "mentor_project_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentor_id" INT NOT NULL,
  "project_id" INT NOT NULL,
  "assigned_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mentor_project_mentor 
    FOREIGN KEY ("mentor_id") REFERENCES "mentors" ("id") ON DELETE CASCADE,
  CONSTRAINT fk_mentor_project_project 
    FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE,
  CONSTRAINT unique_mentor_project 
    UNIQUE ("mentor_id", "project_id")
);


CREATE TABLE IF NOT EXISTS "mentor_workshop_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentor_id" INT NOT NULL,
  "workshop_id" INT NOT NULL,
  "assigned_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_mentor_workshop_mentor 
    FOREIGN KEY ("mentor_id") REFERENCES "mentors" ("id") ON DELETE CASCADE,
  CONSTRAINT fk_mentor_workshop_workshop 
    FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id") ON DELETE CASCADE,
  CONSTRAINT unique_mentor_workshop 
    UNIQUE ("mentor_id", "workshop_id")
);


CREATE INDEX IF NOT EXISTS idx_mentors_user_id ON "mentors"("user_id");
CREATE INDEX IF NOT EXISTS idx_mentors_email ON "mentors"("email");
CREATE INDEX IF NOT EXISTS idx_mentors_expertise ON "mentors"("expertise");
CREATE INDEX IF NOT EXISTS idx_mentors_status ON "mentors"("status");
CREATE INDEX IF NOT EXISTS idx_mentor_projects_mentor ON "mentor_project_assignments"("mentor_id");
CREATE INDEX IF NOT EXISTS idx_mentor_projects_project ON "mentor_project_assignments"("project_id");
CREATE INDEX IF NOT EXISTS idx_mentor_workshops_mentor ON "mentor_workshop_assignments"("mentor_id");
CREATE INDEX IF NOT EXISTS idx_mentor_workshops_workshop ON "mentor_workshop_assignments"("workshop_id");


SELECT 
  'mentors' as table_name,
  COUNT(*) as row_count
FROM mentors
UNION ALL
SELECT 
  'mentor_project_assignments' as table_name,
  COUNT(*) as row_count
FROM mentor_project_assignments
UNION ALL
SELECT 
  'mentor_workshop_assignments' as table_name,
  COUNT(*) as row_count
FROM mentor_workshop_assignments;


SELECT '✅ Mentors tables created successfully!' as status;