-- Migration: Mass Email (UR-B4)
-- email_templates: reusable message templates (acceptance, decline, reminder, ...)
CREATE TABLE IF NOT EXISTS email_templates (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  subject VARCHAR(500) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- email_campaigns: log of every bulk send for audit / re-send tracking
CREATE TABLE IF NOT EXISTS email_campaigns (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  subject VARCHAR(500) NOT NULL,
  body TEXT NOT NULL,
  recipient_source VARCHAR(100) NOT NULL,
  recipient_count INT DEFAULT 0,
  sent_count INT DEFAULT 0,
  status VARCHAR(50) DEFAULT 'pending',
  error TEXT,
  created_by INT,
  created_at TIMESTAMP DEFAULT NOW(),
  sent_at TIMESTAMP
);

-- Template placeholders like {{first_name}} / {{email}} are rendered per-recipient
CREATE INDEX IF NOT EXISTS idx_email_campaigns_created_at ON email_campaigns(created_at DESC);
