CREATE TABLE "static_pages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slug" varchar(100) UNIQUE NOT NULL,
  "title" varchar(255) NOT NULL,
  "body" text NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);