CREATE TABLE IF NOT EXISTS cohort_members (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cohort_id INT NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  current_stage VARCHAR(100) DEFAULT 'idea',
  joined_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(cohort_id, user_id)
);

CREATE TABLE IF NOT EXISTS mentor_assignments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mentor_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entrepreneur_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cohort_id INT NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
  assigned_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(mentor_id, entrepreneur_id, cohort_id)
);

CREATE TABLE IF NOT EXISTS mentor_sessions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id INT NOT NULL REFERENCES mentor_assignments(id) ON DELETE CASCADE,
  session_date DATE NOT NULL,
  notes TEXT,
  feedback TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);