ALTER TABLE funding_requests ADD COLUMN IF NOT EXISTS approved_amount DECIMAL(15,2);
ALTER TABLE funding_requests ADD COLUMN IF NOT EXISTS founder_action VARCHAR(50) DEFAULT 'Pending';

CREATE TABLE IF NOT EXISTS funding_status_history (
                                                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      funding_id INT REFERENCES funding_requests(id) ON DELETE CASCADE,
    acted_by_user_id INT REFERENCES users(id),
    actor_role VARCHAR(50),
    status VARCHAR(50),
    notes TEXT,
    created_at TIMESTAMP DEFAULT now()
    );