-- 1. Create the project status history table
CREATE TABLE IF NOT EXISTS project_status_history (
                                                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      project_id INT REFERENCES projects(id) ON DELETE CASCADE,
    acted_by_user_id INT REFERENCES users(id),
    actor_role VARCHAR(50), -- 'Admin' or 'Founder'
    status VARCHAR(50), -- 'Approved', 'Pending', etc.
    notes TEXT,
    created_at TIMESTAMP DEFAULT now()
    );

-- 2. Add a column to track the founder's action on a project (optional, but good for parity with funding)
ALTER TABLE projects ADD COLUMN IF NOT EXISTS founder_action VARCHAR(50) DEFAULT 'Pending';