-- Direct messaging between users (Telegram-style chat: contact list + thread).
-- Who can message whom is enforced in application code (backend/admin-backend/chat/chat.js):
--   - admin/superadmin can message anyone
--   - anyone can message admin/superadmin
--   - mentor <-> entrepreneur can message each other only if linked via mentor_assignments

CREATE TABLE IF NOT EXISTS messages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  read_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver ON messages(receiver_id);
-- Speeds up "conversation between A and B" lookups regardless of who sent which message.
CREATE INDEX IF NOT EXISTS idx_messages_pair ON messages(sender_id, receiver_id, created_at);
